##
##  Makefile -- Build procedure for sample amazon_proxy Apache module
##  Autogenerated via ``apxs -n amazon_proxy -g''.
##

builddir=.
top_srcdir=/usr
top_builddir=/usr/share/httpd
include /usr/share/httpd/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_amazon_proxy.o mod_amazon_proxy.lo mod_amazon_proxy.slo mod_amazon_proxy.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/amazon_proxy

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

